export const TEMPLATES = [
  {
    id: "forest",
    name: "Ancient Force",
    bg: "#050d08",
    textColor: "#e8f0e4",
    accentColor: "#6db87a",
    preview: "🌲",
  },
  {
    id: "ocean",
    name: "Deep Water",
    bg: "#040c14",
    textColor: "#dceaf5",
    accentColor: "#5b9ec9",
    preview: "🌊",
  },
  {
    id: "moonlight",
    name: "Midnight Edge",
    bg: "#07070f",
    textColor: "#e8e4f5",
    accentColor: "#9b8fd4",
    preview: "🌕",
  },
  {
    id: "sakura",
    name: "Silent Bloom",
    bg: "#100a0d",
    textColor: "#f5e8ee",
    accentColor: "#c97a96",
    preview: "🌸",
  },
  {
    id: "city",
    name: "Urban Empire",
    bg: "#08080c",
    textColor: "#ededf5",
    accentColor: "#c9a96e",
    preview: "🌃",
  },
  {
    id: "gym",
    name: "Iron Will",
    bg: "#0a0806",
    textColor: "#f0ebe4",
    accentColor: "#c96e4a",
    preview: "⚡",
  },
];
